version: "3.9"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - "8096:8096"
    volumes:
      - ./services/jellyfin/config:/config
      - ./media:/media
    restart: unless-stopped
    networks:
      - blorakitron
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    ports:
      - "8989:8989"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./services/sonarr/config:/config
      - ./downloads:/downloads
      - ./media/tv:/tv
    restart: unless-stopped
    networks:
      - blorakitron
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    ports:
      - "7878:7878"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./services/radarr/config:/config
      - ./downloads:/downloads
      - ./media/movies:/movies
    restart: unless-stopped
    networks:
      - blorakitron
  transmission:
    build:
      context: .
      dockerfile: ./.docker/DockerfileTransmission
    container_name: transmission
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASSWORD}
    volumes:
      - ./services/transmission/config:/config
      - ./services/transmission/watch:/watch
      - ./downloads:/downloads
    restart: unless-stopped
    networks:
      - blorakitron
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    ports:
      - "9117:9117"
    environment:
      - PUID={PUID}
      - PGID={PGID}
      - TZ=${TZ}
    volumes:
      - ./services/jackett/config:/config
      - ./downloads:/downloads
    restart: unless-stopped
    networks:
      - blorakitron
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./services/cloudflared/config:/etc/cloudflared
    command: tunnel --config /etc/cloudflared/config.yml run
    networks:
      - blorakitron
  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SUBDOMAINS=TZ=${DUCKDNS_SUBDOMAIN}
      - TOKEN=${DUCKDNS_TOKEN}
    restart: unless-stopped
    networks:
      - blorakitron
networks:
  blorakitron:
    external: false