version: "3.9"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - "8096:8096"
    volumes:
      - ./services/jellyfin/config:/config
      - ./services/jellyfin/media:/media
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    ports:
      - "8989:8989"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./services/sonarr/config:/config
      - ./services/transmission/downloads:/downloads
      - ./services/jellyfin/media/tv:/tv
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    ports:
      - "7878:7878"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./services/radarr/config:/config
      - ./services/transmission/downloads:/downloads
      - ./services/jellyfin/media/movies:/movies
    restart: unless-stopped
  transmission:
    build:
      context: .
      dockerfile: ./docker/DockerfileTransmission
    container_name: transmission
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASSWORD}
    volumes:
      - ./services/transmission/downloads:/downloads
      - ./services/transmission/config:/config
      - ./services/transmission/watch:/watch
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    ports:
      - "9117:9117"
    environment:
      - PUID={PUID}
      - PGID={PGID}
      - TZ=${TZ}
    volumes:
      - ./services/jackett/config:/config
      - ./services/jackett/downloads:/downloads
    restart: unless-stopped